backend:
  name: github
  repo: PMASTUDIO/personal-ib-blog

media_folder: content/assets
public_folder: ../assets
locale: "es"

collections:
  - name: blog
    label: Blog Post
    folder: content/blog
    create: true
    fields:
      - { name: published, label: Published, widget: boolean, default: false }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
